export const urls = {
  homePage: 'https://candymapper.com/',
  twoFactorAuthPage: 'https://candymapper.com/2fa-validation-code',
  joinUs: 'https://candymapper.com/m/login?r=%2Fjoin-us',
  bcs: 'https://www.bcs.org/',
  halloweenParty: 'https://candymapper.com/halloween-party',
  hostParty: 'https://candymapper.com/host-a-party-1',
  attendParty: 'https://candymapper.com/attend-a-party',
  partyLocation: 'https://candymapper.com/party-location',
  error404: 'https://candymapper.com/error-404',
  launchCandyMapper: 'https://candymapper.com/launch-candymapper',
  keysight: 'https://www.keysight.com/blogs/en/authors/jonathon-wright',
  packtPublishing:
    'https://www.packtpub.com/en-us/product/enhanced-test-automation-with-webdriverio-9781837630189',
  findMyCandy: 'https://candymapper.com/find-my-candy',
  automationSandbox: 'https://candymapper.com/an-automation-sandbox%3F',
  graveyardLinks: 'https://candymapperr2.com/',
  magicObjectModel: 'https://candymapper.com/magic-object-model%3F',
  sandboxTools: 'https://candymapper.com/sandbox-tools',
  vampirasBlog: 'https://candymapper.com/vampiras-blog',
};
